In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

import os

import haversine as hs

from datetime import datetime, timedelta

import numpy as np

In [2]:
from IPython.display import display

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [3]:
race_info = pd.read_csv("F1_23_Planned.csv")

race_info.shape

(24, 15)

In [4]:
race_info.head()

,year,round,race,date,country,location,circuit,circuitRef,header,gap,distance (km),lat,lng,raceId,circuitId
0,2023,1,Bahrain Grand Prix,2023-03-05,Bahrain,Sakhir,Bahrain International Circuit,bahrain,single,0,0.00,26.0325,50.5106,1098,3
1,2023,2,Saudi Arabian Grand Prix,2023-03-19,Saudi Arabia,Jeddah,Jeddah Corniche Circuit,jeddah,single,2,1258.43,21.6319,39.1044,1099,77
2,2023,3,Australian Grand Prix,2023-04-02,Australia,Melbourne,Albert Park Grand Prix Circuit,albert_park,single,2,12817.12,-37.8497,144.9680,1100,1
3,2023,4,Chinese Grand Prix,2023-04-16,China,Shanghai,Shanghai International Circuit,shanghai,single,2,8078.46,31.3389,121.2200,1012,17
4,2023,5,Azerbaijan Grand Prix,2023-04-30,Azerbaijan,Baku,Baku City Circuit,baku,double,2,6336.88,40.3725,49.8533,1101,73

In [5]:
f1_23 = race_info.loc[race_info['year'] == 2023]

f1_23

,year,round,race,date,country,location,circuit,circuitRef,header,gap,distance (km),lat,lng,raceId,circuitId
0,2023,1,Bahrain Grand Prix,2023-03-05,Bahrain,Sakhir,Bahrain International Circuit,bahrain,single,0,0.00,26.0325,50.51060,1098,3
1,2023,2,Saudi Arabian Grand Prix,2023-03-19,Saudi Arabia,Jeddah,Jeddah Corniche Circuit,jeddah,single,2,1258.43,21.6319,39.10440,1099,77
2,2023,3,Australian Grand Prix,2023-04-02,Australia,Melbourne,Albert Park Grand Prix Circuit,albert_park,single,2,12817.12,-37.8497,144.96800,1100,1
3,2023,4,Chinese Grand Prix,2023-04-16,China,Shanghai,Shanghai International Circuit,shanghai,single,2,8078.46,31.3389,121.22000,1012,17
4,2023,5,Azerbaijan Grand Prix,2023-04-30,Azerbaijan,Baku,Baku City Circuit,baku,double,2,6336.88,40.3725,49.85330,1101,73
5,2023,6,Miami Grand Prix,2023-05-07,USA,Miami,Miami International Autodrome,miami,double,1,11015.93,25.9581,-80.23890,1102,79
6,2023,7,Emilia Romagna Grand Prix,2023-05-21,Italy,Imola,Autodromo Enzo e Dino Ferrari,imola,triple,2,8172.92,44.3439,11.71670,1077,21
7,2023,8,Monaco Grand Prix,2023-05-28,Monaco,Monte-Carlo,Circuit de Monaco,monaco,triple,1,349.98,43.7347,7.42056,1104,6
8,2023,9,Spanish Grand Prix,2023-06-04,Spain,Montmeló,Circuit de Barcelona-Catalunya,catalunya,triple,1,485.64,41.5700,2.26111,1105,4
9,2023,10,Canadian Grand Prix,2023-06-18,Canada,Montreal,Circuit Gilles Villeneuve,villeneuve,single,2,5891.51,45.5000,-73.52280,1106,7
10,2023,11,Austrian Grand Prix,2023-07-02,Austria,Spielberg,Red Bull Ring,red_bull_ring,double,2,6390.49,47.2197,14.76470,1107,70
11,2023,12,British Grand Prix,2023-07-09,UK,Silverstone,Silverstone Circuit,silverstone,double,1,1254.64,52.0786,-1.01694,1108,9
12,2023,13,Hungarian Grand Prix,2023-07-23,Hungary,Budapest,Hungaroring,hungaroring,double,2,1531.29,47.5789,19.24860,1109,11
13,2023,14,Belgian Grand Prix,2023-07-30,Belgium,Spa,Circuit de Spa-Francorchamps,spa,double,1,1017.59,50.4372,5.97139,1110,13
14,2023,15,Dutch Grand Prix,2023-08-27,Netherlands,Zandvoort,Circuit Park Zandvoort,zandvoort,double,4,238.60,52.3888,4.54092,1111,39
15,2023,16,Italian Grand Prix,2023-09-03,Italy,Monza,Autodromo Nazionale di Monza,monza,double,1,828.29,45.6156,9.28111,1112,14
16,2023,17,Singapore Grand Prix,2023-09-17,Singapore,Marina Bay,Marina Bay Street Circuit,marina_bay,double,2,10260.98,1.2914,103.86400,1113,15
17,2023,18,Japanese Grand Prix,2023-09-24,Japan,Suzuka,Suzuka Circuit,suzuka,double,1,5035.99,34.8431,136.54100,1114,22
18,2023,19,Qatar Grand Prix,2023-10-08,Qatar,Al Daayen,Losail International Circuit,losail,single,2,8003.99,25.4900,51.45420,1115,78
19,2023,20,United States Grand Prix,2023-10-22,USA,Austin,Circuit of the Americas,americas,triple,2,13008.46,30.1328,-97.64110,1116,69
20,2023,21,Mexico City Grand Prix,2023-10-29,Mexico,Mexico City,Autódromo Hermanos Rodríguez,rodriguez,triple,1,1201.87,19.4042,-99.09070,1117,32
21,2023,22,São Paulo Grand Prix,2023-11-05,Brazil,São Paulo,Autódromo José Carlos Pace,interlagos,triple,1,7430.98,-23.7036,-46.69970,1118,18
22,2023,23,Las Vegas Grand Prix,2023-11-19,USA,Las Vegas,Las Vegas Strip Street Circuit,vegas,double,2,9787.88,36.1147,-115.17300,1119,80
23,2023,24,Abu Dhabi Grand Prix,2023-11-26,UAE,Abu Dhabi,Yas Marina Circuit,yas_marina,double,1,13193.63,24.4672,54.60310,1120,24

In [6]:
def dist(lat1, lng1, lat2, lng2):
    
    distance = hs.haversine((lat1, lng1), (lat2, lng2))
    
    return round(distance, 2)

In [7]:
concorde = ['São Paulo', 'Miami', 'Mexico City', 'Austin', 'Las Vegas', 'Montreal', 'Silverstone', 'Zandvoort', 'Spa', 'Montmeló', 'Monte-Carlo', 'Monza', 'Imola', 'Spielberg', 'Budapest', 'Jeddah', 'Sakhir', 'Al Daayen', 'Abu Dhabi', 'Baku', 'Suzuka', 'Shanghai', 'Marina Bay', 'Melbourne']

In [ ]:
i = 9

print(concorde[i:])
print()
print(concorde[:i])

In [8]:
def tsp(locations):
    
    total_dist = 0
    start = locations[0]
    distance = 0
    
    #print(start, distance, total_dist)
    
    for location in locations[1:]:
        
        lat1 = f1_23.loc[f1_23['location'] == start, 'lat'].values[0]
        lng1 = f1_23.loc[f1_23['location'] == start, 'lng'].values[0]
        
        lat2 = f1_23.loc[f1_23['location'] == location, 'lat'].values[0]
        lng2 = f1_23.loc[f1_23['location'] == location, 'lng'].values[0]
        
        distance = dist(lat1, lng1, lat2, lng2)
        
        start = location
        total_dist = total_dist + distance
        
        #print(location, round(distance, 2), round(total_dist, 2))
    
    #print()
    #print("Total distance :", round(total_dist, 2))
    
    return(round(total_dist, 2))

In [9]:
tsp(concorde)

49337.02

In [10]:
size = len(concorde)
print(size)
print()

for i in range(0, 24):
    #print(i)
    #print(concorde[i:] + concorde[:i])
    #print(i, len(concorde[i:] + concorde[:i]))
    
    locations = concorde[i:] + concorde[:i]
    
    distance = tsp(locations)
    
    print(i, locations[0], '-',locations[-1], distance)
    print()

24

0 São Paulo - Melbourne 49337.02

1 Miami - São Paulo 55803.78

2 Mexico City - Miami 60335.83

3 Austin - Mexico City 61198.08

4 Las Vegas - Austin 60640.34

5 Montreal - Las Vegas 58787.19

6 Silverstone - Montreal 57262.73

7 Zandvoort - Silverstone 62019.98

8 Spa - Zandvoort 62161.35

9 Montmeló - Spa 61373.5

10 Monte-Carlo - Montmeló 61914.31

11 Monza - Monte-Carlo 62144.26

12 Imola - Monza 62161.86

13 Spielberg - Imola 62002.37

14 Budapest - Spielberg 62060.16

15 Jeddah - Budapest 59012.16

16 Sakhir - Jeddah 61141.52

17 Al Daayen - Sakhir 62287.84

18 Abu Dhabi - Al Daayen 62062.81

19 Baku - Abu Dhabi 60576.82

20 Suzuka - Baku 55057.4

21 Shanghai - Suzuka 60922.14

22 Marina Bay - Shanghai 58593.14

23 Melbourne - Marina Bay 56342.26

In [11]:
def nearest(circuits, parsed):
    start = parsed[-1]
    min_dist = float("inf")
    
    for circuit in circuits:
        if circuit in parsed:
            continue
        
        lat1 = f1_23.loc[f1_23['circuitRef'] == start, 'lat'].values[0]
        lng1 = f1_23.loc[f1_23['circuitRef'] == start, 'lng'].values[0]
        
        lat2 = f1_23.loc[f1_23['circuitRef'] == circuit, 'lat'].values[0]
        lng2 = f1_23.loc[f1_23['circuitRef'] == circuit, 'lng'].values[0]
        
        distance = dist(lat1, lng1, lat2, lng2)
        
        if distance < min_dist:
            min_dist = distance
            next_loc = circuit
        
    return(next_loc, min_dist)

In [ ]:
def furthest(locations, parsed):
    start = parsed[-1]
    max_dist = 0
    
    for location in locations:
        if location in parsed:
            continue
        
        lat1 = f1_23.loc[f1_23['location'] == start, 'lat'].values[0]
        lng1 = f1_23.loc[f1_23['location'] == start, 'lng'].values[0]
        
        lat2 = f1_23.loc[f1_23['location'] == location, 'lat'].values[0]
        lng2 = f1_23.loc[f1_23['location'] == location, 'lng'].values[0]
        
        distance = dist(lat1, lng1, lat2, lng2)
        
        if distance > max_dist:
            max_dist = distance
            next_loc = location
        
    return(next_loc, max_dist)

In [ ]:
locations = f1_23['location'].values.tolist()

print(locations)

In [ ]:
parsed = list()

start = locations[0]
parsed.append(start)

total = 0

print(start, 0)

for location in locations:
    
    #print(parsed, "\n")
    
    if len(parsed) != len(locations):
        next_loc, distance = nearest(locations, parsed)
        parsed.append(next_loc)
        total = total + distance
        print(next_loc, distance, "kms")
    

#print(parsed)
print("\nTotal distance :", round(total, 2))

In [ ]:
parsed = list()

start = locations[0]
parsed.append(start)

total = 0

print(start, 0)

for location in locations:
    
    #print(parsed, "\n")
    
    if len(parsed) != len(locations):
        next_loc, distance = furthest(locations, parsed)
        parsed.append(next_loc)
        total = total + distance
        print(next_loc, distance, "kms")
    

#print(parsed)
print("\nTotal distance :", round(total, 2))

In [ ]:
def furthest_calendar(start, display=False):
    parsed = list()

    #start = locations[0]
    parsed.append(start)

    total = 0
    
    if display == True:
        print(start, 0)
    
    for location in locations:
    
        #print(parsed, "\n")
    
        if len(parsed) != len(locations):
            next_loc, distance = furthest(locations, parsed)
            parsed.append(next_loc)
            total = total + distance
            
            if display == True:
                print(next_loc, distance, "kms")
    
    if display == False:
        return parsed, total
    else:
        print("\nTotal distance :", round(total, 2), "kms")

In [ ]:
max_tot = 0

for location in locations:
    parsed, total = furthest_calendar(location)
    
    print(location, round(total, 2), "kms")
    
    if total > max_tot:
        max_tot = total
        best_start = location

print("\nWorst start :", best_start)
print("Total distance :", round(max_tot, 2), "kms")

In [ ]:
furthest_calendar("Monza", display=True)

In [12]:
def nearest_calendar(start, circs, display=False):
    parsed = list()

    #start = locations[0]
    parsed.append(start)

    total = 0
    
    if display == True:
        print(start, 0)
    
    for circuit in circs:
    
        #print(parsed, "\n")
    
        if len(parsed) != len(circs):
            next_loc, distance = nearest(circs, parsed)
            parsed.append(next_loc)
            total = total + distance
            
            if display == True:
                print(next_loc, distance, "kms")
    
    if display == False:
        return parsed, total
    else:
        print("\nTotal distance :", round(total, 2), "kms")

In [14]:
min_tot = float("inf")

for location in locations:
    parsed, total = nearest_calendar(location, locations)
    
    print(location, round(total, 2), "kms")
    
    if total < min_tot:
        min_tot = total
        best_start = location

print("\nBest start :", best_start)
print("Total distance :", round(min_tot, 2), "kms")

IndexError: index 0 is out of bounds for axis 0 with size 0

In [15]:
locations

['Melbourne',
 'São Paulo',
 'Miami',
 'Mexico City',
 'Austin',
 'Las Vegas',
 'Montreal',
 'Silverstone',
 'Zandvoort',
 'Spa',
 'Montmeló',
 'Monte-Carlo',
 'Monza',
 'Imola',
 'Spielberg',
 'Budapest',
 'Jeddah',
 'Sakhir',
 'Al Daayen',
 'Abu Dhabi',
 'Baku',
 'Suzuka',
 'Shanghai',
 'Marina Bay']

In [16]:
circuits = f1_23['circuitRef'].values.tolist()

In [17]:
distances = pd.DataFrame(columns = circuits)

In [18]:
distances

Empty DataFrame
Columns: [bahrain, jeddah, albert_park, shanghai, baku, miami, imola, monaco, catalunya, villeneuve, red_bull_ring, silverstone, hungaroring, spa, zandvoort, monza, marina_bay, suzuka, losail, americas, rodriguez, interlagos, vegas, yas_marina]
Index: []

In [19]:
f1_23

,year,round,race,date,country,location,circuit,circuitRef,header,gap,distance (km),lat,lng,raceId,circuitId
0,2023,1,Bahrain Grand Prix,2023-03-05,Bahrain,Sakhir,Bahrain International Circuit,bahrain,single,0,0.00,26.0325,50.51060,1098,3
1,2023,2,Saudi Arabian Grand Prix,2023-03-19,Saudi Arabia,Jeddah,Jeddah Corniche Circuit,jeddah,single,2,1258.43,21.6319,39.10440,1099,77
2,2023,3,Australian Grand Prix,2023-04-02,Australia,Melbourne,Albert Park Grand Prix Circuit,albert_park,single,2,12817.12,-37.8497,144.96800,1100,1
3,2023,4,Chinese Grand Prix,2023-04-16,China,Shanghai,Shanghai International Circuit,shanghai,single,2,8078.46,31.3389,121.22000,1012,17
4,2023,5,Azerbaijan Grand Prix,2023-04-30,Azerbaijan,Baku,Baku City Circuit,baku,double,2,6336.88,40.3725,49.85330,1101,73
5,2023,6,Miami Grand Prix,2023-05-07,USA,Miami,Miami International Autodrome,miami,double,1,11015.93,25.9581,-80.23890,1102,79
6,2023,7,Emilia Romagna Grand Prix,2023-05-21,Italy,Imola,Autodromo Enzo e Dino Ferrari,imola,triple,2,8172.92,44.3439,11.71670,1077,21
7,2023,8,Monaco Grand Prix,2023-05-28,Monaco,Monte-Carlo,Circuit de Monaco,monaco,triple,1,349.98,43.7347,7.42056,1104,6
8,2023,9,Spanish Grand Prix,2023-06-04,Spain,Montmeló,Circuit de Barcelona-Catalunya,catalunya,triple,1,485.64,41.5700,2.26111,1105,4
9,2023,10,Canadian Grand Prix,2023-06-18,Canada,Montreal,Circuit Gilles Villeneuve,villeneuve,single,2,5891.51,45.5000,-73.52280,1106,7
10,2023,11,Austrian Grand Prix,2023-07-02,Austria,Spielberg,Red Bull Ring,red_bull_ring,double,2,6390.49,47.2197,14.76470,1107,70
11,2023,12,British Grand Prix,2023-07-09,UK,Silverstone,Silverstone Circuit,silverstone,double,1,1254.64,52.0786,-1.01694,1108,9
12,2023,13,Hungarian Grand Prix,2023-07-23,Hungary,Budapest,Hungaroring,hungaroring,double,2,1531.29,47.5789,19.24860,1109,11
13,2023,14,Belgian Grand Prix,2023-07-30,Belgium,Spa,Circuit de Spa-Francorchamps,spa,double,1,1017.59,50.4372,5.97139,1110,13
14,2023,15,Dutch Grand Prix,2023-08-27,Netherlands,Zandvoort,Circuit Park Zandvoort,zandvoort,double,4,238.60,52.3888,4.54092,1111,39
15,2023,16,Italian Grand Prix,2023-09-03,Italy,Monza,Autodromo Nazionale di Monza,monza,double,1,828.29,45.6156,9.28111,1112,14
16,2023,17,Singapore Grand Prix,2023-09-17,Singapore,Marina Bay,Marina Bay Street Circuit,marina_bay,double,2,10260.98,1.2914,103.86400,1113,15
17,2023,18,Japanese Grand Prix,2023-09-24,Japan,Suzuka,Suzuka Circuit,suzuka,double,1,5035.99,34.8431,136.54100,1114,22
18,2023,19,Qatar Grand Prix,2023-10-08,Qatar,Al Daayen,Losail International Circuit,losail,single,2,8003.99,25.4900,51.45420,1115,78
19,2023,20,United States Grand Prix,2023-10-22,USA,Austin,Circuit of the Americas,americas,triple,2,13008.46,30.1328,-97.64110,1116,69
20,2023,21,Mexico City Grand Prix,2023-10-29,Mexico,Mexico City,Autódromo Hermanos Rodríguez,rodriguez,triple,1,1201.87,19.4042,-99.09070,1117,32
21,2023,22,São Paulo Grand Prix,2023-11-05,Brazil,São Paulo,Autódromo José Carlos Pace,interlagos,triple,1,7430.98,-23.7036,-46.69970,1118,18
22,2023,23,Las Vegas Grand Prix,2023-11-19,USA,Las Vegas,Las Vegas Strip Street Circuit,vegas,double,2,9787.88,36.1147,-115.17300,1119,80
23,2023,24,Abu Dhabi Grand Prix,2023-11-26,UAE,Abu Dhabi,Yas Marina Circuit,yas_marina,double,1,13193.63,24.4672,54.60310,1120,24

In [20]:
for cir1 in circuits:
    #print(loc1)
    lat1 = f1_23.loc[f1_23['circuitRef'] == cir1, 'lat'].values[0]
    lng1 = f1_23.loc[f1_23['circuitRef'] == cir1, 'lng'].values[0]
    
    for cir2 in circuits:
        print(cir1, cir2)
        lat2 = f1_23.loc[f1_23['circuitRef'] == cir2, 'lat'].values[0]
        lng2 = f1_23.loc[f1_23['circuitRef'] == cir2, 'lng'].values[0]
        
        distance = dist(lat1, lng1, lat2, lng2)
        
        distances.loc[cir1, cir2] = distance

bahrain bahrain
bahrain jeddah
bahrain albert_park
bahrain shanghai
bahrain baku
bahrain miami
bahrain imola
bahrain monaco
bahrain catalunya
bahrain villeneuve
bahrain red_bull_ring
bahrain silverstone
bahrain hungaroring
bahrain spa
bahrain zandvoort
bahrain monza
bahrain marina_bay
bahrain suzuka
bahrain losail
bahrain americas
bahrain rodriguez
bahrain interlagos
bahrain vegas
bahrain yas_marina
jeddah bahrain
jeddah jeddah
jeddah albert_park
jeddah shanghai
jeddah baku
jeddah miami
jeddah imola
jeddah monaco
jeddah catalunya
jeddah villeneuve
jeddah red_bull_ring
jeddah silverstone
jeddah hungaroring
jeddah spa
jeddah zandvoort
jeddah monza
jeddah marina_bay
jeddah suzuka
jeddah losail
jeddah americas
jeddah rodriguez
jeddah interlagos
jeddah vegas
jeddah yas_marina
albert_park bahrain
albert_park jeddah
albert_park albert_park
albert_park shanghai
albert_park baku
albert_park miami
albert_park imola
albert_park monaco
albert_park catalunya
albert_park villeneuve
albert_park red_bull_ring
albert_park silverstone
albert_park hungaroring
albert_park spa
albert_park zandvoort
albert_park monza
albert_park marina_bay
albert_park suzuka
albert_park losail
albert_park americas
albert_park rodriguez
albert_park interlagos
albert_park vegas
albert_park yas_marina
shanghai bahrain
shanghai jeddah
shanghai albert_park
shanghai shanghai
shanghai baku
shanghai miami
shanghai imola
shanghai monaco
shanghai catalunya
shanghai villeneuve
shanghai red_bull_ring
shanghai silverstone
shanghai hungaroring
shanghai spa
shanghai zandvoort
shanghai monza
shanghai marina_bay
shanghai suzuka
shanghai losail
shanghai americas
shanghai rodriguez
shanghai interlagos
shanghai vegas
shanghai yas_marina
baku bahrain
baku jeddah
baku albert_park
baku shanghai
baku baku
baku miami
baku imola
baku monaco
baku catalunya
baku villeneuve
baku red_bull_ring
baku silverstone
baku hungaroring
baku spa
baku zandvoort
baku monza
baku marina_bay
baku suzuka
baku losail
baku americas
baku rodriguez
baku interlagos
baku vegas
baku yas_marina
miami bahrain
miami jeddah
miami albert_park
miami shanghai
miami baku
miami miami
miami imola
miami monaco
miami catalunya
miami villeneuve
miami red_bull_ring
miami silverstone
miami hungaroring
miami spa
miami zandvoort
miami monza
miami marina_bay
miami suzuka
miami losail
miami americas
miami rodriguez
miami interlagos
miami vegas
miami yas_marina
imola bahrain
imola jeddah
imola albert_park
imola shanghai
imola baku
imola miami
imola imola
imola monaco
imola catalunya
imola villeneuve
imola red_bull_ring
imola silverstone
imola hungaroring
imola spa
imola zandvoort
imola monza
imola marina_bay
imola suzuka
imola losail
imola americas
imola rodriguez
imola interlagos
imola vegas
imola yas_marina
monaco bahrain
monaco jeddah
monaco albert_park
monaco shanghai
monaco baku
monaco miami
monaco imola
monaco monaco
monaco catalunya
monaco villeneuve
monaco red_bull_ring
monaco silverstone
monaco hungaroring
monaco spa
monaco zandvoort
monaco monza
monaco marina_bay
monaco suzuka
monaco losail
monaco americas
monaco rodriguez
monaco interlagos
monaco vegas
monaco yas_marina
catalunya bahrain
catalunya jeddah
catalunya albert_park
catalunya shanghai
catalunya baku
catalunya miami
catalunya imola
catalunya monaco
catalunya catalunya
catalunya villeneuve
catalunya red_bull_ring
catalunya silverstone
catalunya hungaroring
catalunya spa
catalunya zandvoort
catalunya monza
catalunya marina_bay
catalunya suzuka
catalunya losail
catalunya americas
catalunya rodriguez
catalunya interlagos
catalunya vegas
catalunya yas_marina
villeneuve bahrain
villeneuve jeddah
villeneuve albert_park
villeneuve shanghai
villeneuve baku
villeneuve miami
villeneuve imola
villeneuve monaco
villeneuve catalunya
villeneuve villeneuve
villeneuve red_bull_ring
villeneuve silverstone
villeneuve hungaroring
villeneuve spa
villeneuve zandvoort
villeneuve monza
villeneuve marina_bay
villeneuve suzuka
villeneuve losail
villeneuve americas
villeneuve rodriguez
villeneuve interlagos
villeneuve vegas
villeneuve yas_marina
red_bull_ring bahrain
red_bull_ring jeddah
red_bull_ring albert_park
red_bull_ring shanghai
red_bull_ring baku
red_bull_ring miami
red_bull_ring imola
red_bull_ring monaco
red_bull_ring catalunya
red_bull_ring villeneuve
red_bull_ring red_bull_ring
red_bull_ring silverstone
red_bull_ring hungaroring
red_bull_ring spa
red_bull_ring zandvoort
red_bull_ring monza
red_bull_ring marina_bay
red_bull_ring suzuka
red_bull_ring losail
red_bull_ring americas
red_bull_ring rodriguez
red_bull_ring interlagos
red_bull_ring vegas
red_bull_ring yas_marina
silverstone bahrain
silverstone jeddah
silverstone albert_park
silverstone shanghai
silverstone baku
silverstone miami
silverstone imola
silverstone monaco
silverstone catalunya
silverstone villeneuve
silverstone red_bull_ring
silverstone silverstone
silverstone hungaroring
silverstone spa
silverstone zandvoort
silverstone monza
silverstone marina_bay
silverstone suzuka
silverstone losail
silverstone americas
silverstone rodriguez
silverstone interlagos
silverstone vegas
silverstone yas_marina
hungaroring bahrain
hungaroring jeddah
hungaroring albert_park
hungaroring shanghai
hungaroring baku
hungaroring miami
hungaroring imola
hungaroring monaco
hungaroring catalunya
hungaroring villeneuve
hungaroring red_bull_ring
hungaroring silverstone
hungaroring hungaroring
hungaroring spa
hungaroring zandvoort
hungaroring monza
hungaroring marina_bay
hungaroring suzuka
hungaroring losail
hungaroring americas
hungaroring rodriguez
hungaroring interlagos
hungaroring vegas
hungaroring yas_marina
spa bahrain
spa jeddah
spa albert_park
spa shanghai
spa baku
spa miami
spa imola
spa monaco
spa catalunya
spa villeneuve
spa red_bull_ring
spa silverstone
spa hungaroring
spa spa
spa zandvoort
spa monza
spa marina_bay
spa suzuka
spa losail
spa americas
spa rodriguez
spa interlagos
spa vegas
spa yas_marina
zandvoort bahrain
zandvoort jeddah
zandvoort albert_park
zandvoort shanghai
zandvoort baku
zandvoort miami
zandvoort imola
zandvoort monaco
zandvoort catalunya
zandvoort villeneuve
zandvoort red_bull_ring
zandvoort silverstone
zandvoort hungaroring
zandvoort spa
zandvoort zandvoort
zandvoort monza
zandvoort marina_bay
zandvoort suzuka
zandvoort losail
zandvoort americas
zandvoort rodriguez
zandvoort interlagos
zandvoort vegas
zandvoort yas_marina
monza bahrain
monza jeddah
monza albert_park
monza shanghai
monza baku
monza miami
monza imola
monza monaco
monza catalunya
monza villeneuve
monza red_bull_ring
monza silverstone
monza hungaroring
monza spa
monza zandvoort
monza monza
monza marina_bay
monza suzuka
monza losail
monza americas
monza rodriguez
monza interlagos
monza vegas
monza yas_marina
marina_bay bahrain
marina_bay jeddah
marina_bay albert_park
marina_bay shanghai
marina_bay baku
marina_bay miami
marina_bay imola
marina_bay monaco
marina_bay catalunya
marina_bay villeneuve
marina_bay red_bull_ring
marina_bay silverstone
marina_bay hungaroring
marina_bay spa
marina_bay zandvoort
marina_bay monza
marina_bay marina_bay
marina_bay suzuka
marina_bay losail
marina_bay americas
marina_bay rodriguez
marina_bay interlagos
marina_bay vegas
marina_bay yas_marina
suzuka bahrain
suzuka jeddah
suzuka albert_park
suzuka shanghai
suzuka baku
suzuka miami
suzuka imola
suzuka monaco
suzuka catalunya
suzuka villeneuve
suzuka red_bull_ring
suzuka silverstone
suzuka hungaroring
suzuka spa
suzuka zandvoort
suzuka monza
suzuka marina_bay
suzuka suzuka
suzuka losail
suzuka americas
suzuka rodriguez
suzuka interlagos
suzuka vegas
suzuka yas_marina
losail bahrain
losail jeddah
losail albert_park
losail shanghai
losail baku
losail miami
losail imola
losail monaco
losail catalunya
losail villeneuve
losail red_bull_ring
losail silverstone
losail hungaroring
losail spa
losail zandvoort
losail monza
losail marina_bay
losail suzuka
losail losail
losail americas
losail rodriguez
losail interlagos
losail vegas
losail yas_marina
americas bahrain
americas jeddah
americas albert_park
americas shanghai
americas baku
americas miami
americas imola
americas monaco
americas catalunya
americas villeneuve
americas red_bull_ring
americas silverstone
americas hungaroring
americas spa
americas zandvoort
americas monza
americas marina_bay
americas suzuka
americas losail
americas americas
americas rodriguez
americas interlagos
americas vegas
americas yas_marina
rodriguez bahrain
rodriguez jeddah
rodriguez albert_park
rodriguez shanghai
rodriguez baku
rodriguez miami
rodriguez imola
rodriguez monaco
rodriguez catalunya
rodriguez villeneuve
rodriguez red_bull_ring
rodriguez silverstone
rodriguez hungaroring
rodriguez spa
rodriguez zandvoort
rodriguez monza
rodriguez marina_bay
rodriguez suzuka
rodriguez losail
rodriguez americas
rodriguez rodriguez
rodriguez interlagos
rodriguez vegas
rodriguez yas_marina
interlagos bahrain
interlagos jeddah
interlagos albert_park
interlagos shanghai
interlagos baku
interlagos miami
interlagos imola
interlagos monaco
interlagos catalunya
interlagos villeneuve
interlagos red_bull_ring
interlagos silverstone
interlagos hungaroring
interlagos spa
interlagos zandvoort
interlagos monza
interlagos marina_bay
interlagos suzuka
interlagos losail
interlagos americas
interlagos rodriguez
interlagos interlagos
interlagos vegas
interlagos yas_marina
vegas bahrain
vegas jeddah
vegas albert_park
vegas shanghai
vegas baku
vegas miami
vegas imola
vegas monaco
vegas catalunya
vegas villeneuve
vegas red_bull_ring
vegas silverstone
vegas hungaroring
vegas spa
vegas zandvoort
vegas monza
vegas marina_bay
vegas suzuka
vegas losail
vegas americas
vegas rodriguez
vegas interlagos
vegas vegas
vegas yas_marina
yas_marina bahrain
yas_marina jeddah
yas_marina albert_park
yas_marina shanghai
yas_marina baku
yas_marina miami
yas_marina imola
yas_marina monaco
yas_marina catalunya
yas_marina villeneuve
yas_marina red_bull_ring
yas_marina silverstone
yas_marina hungaroring
yas_marina spa
yas_marina zandvoort
yas_marina monza
yas_marina marina_bay
yas_marina suzuka
yas_marina losail
yas_marina americas
yas_marina rodriguez
yas_marina interlagos
yas_marina vegas
yas_marina yas_marina

In [21]:
distances

,bahrain,jeddah,albert_park,shanghai,baku,miami,imola,monaco,catalunya,villeneuve,red_bull_ring,silverstone,hungaroring,spa,zandvoort,monza,marina_bay,suzuka,losail,americas,rodriguez,interlagos,vegas,yas_marina
bahrain,0.0,1258.43,12112.63,6804.82,1595.7,12185.63,4018.27,4332.65,4710.93,10258.97,3910.84,5158.08,3628.99,4640.39,4805.05,4242.73,6327.19,8054.34,112.11,12908.78,13990.13,11813.59,12943.28,446.84
jeddah,1258.43,0.0,12817.12,8062.08,2317.68,11605.63,3559.5,3810.52,4087.37,9929.43,3585.08,4815.75,3387.79,4307.69,4515.1,3797.55,7353.82,9293.32,1329.13,12632.62,13574.58,10555.63,13047.49,1615.85
albert_park,12112.63,12817.12,0.0,8078.46,12989.08,15594.5,16086.36,16422.24,16823.35,16741.1,15878.75,16947.24,15546.43,16511.75,16572.56,16288.08,6057.69,8129.72,12000.56,14286.08,13563.81,13062.93,13131.15,11674.76
shanghai,6804.82,8062.08,8078.46,0.0,6336.88,13248.55,8986.37,9302.0,9779.98,11342.35,8611.28,9175.17,8302.58,8926.2,8867.67,9058.02,3806.81,1477.81,6741.58,12043.14,12920.89,18553.96,10488.07,6494.1
baku,1595.7,2317.68,12989.08,6336.88,0.0,11015.93,3135.79,3484.89,3946.5,8930.53,2890.55,4030.59,2557.38,3545.36,3652.58,3314.42,6946.64,7342.55,1661.51,11489.38,12631.93,12217.83,11373.52,1823.13
miami,12185.63,11605.63,15594.5,13248.55,11015.93,0.0,8172.92,7870.83,7536.29,2253.88,8278.97,7043.58,8573.8,7556.53,7408.92,7945.2,16953.2,12224.22,12295.53,1767.69,2064.12,6596.17,3492.74,12600.1
imola,4018.27,3559.5,16086.36,8986.37,3135.79,8172.92,0.0,349.98,828.38,6372.27,397.58,1273.39,683.89,803.27,1038.66,238.09,10077.87,9598.52,4129.25,9074.91,10054.68,9612.48,9592.05,4443.94
monaco,4332.65,3810.52,16422.24,9302.0,3484.89,7870.83,349.98,0.0,485.64,6121.74,690.95,1119.23,1012.39,753.28,985.59,255.69,10425.06,9874.96,4444.17,8824.3,9778.21,9306.38,9413.94,4763.03
catalunya,4710.93,4087.37,16823.35,9779.98,3946.5,7536.29,828.38,485.64,0.0,5891.51,1173.27,1194.5,1497.97,1026.45,1215.2,722.01,10873.36,10323.61,4822.99,8582.43,9487.42,8834.87,9288.44,5148.63
villeneuve,10258.97,9929.43,16741.1,11342.35,8930.53,2253.88,6372.27,6121.74,5891.51,0.0,6390.49,5137.22,6644.71,5655.01,5470.23,6134.6,14805.77,10584.02,10362.82,2703.19,3731.54,8159.68,3612.76,10635.91
red_bull_ring,3910.84,3585.08,15878.75,8611.28,2890.55,8278.97,397.58,690.95,1173.27,6390.49,0.0,1254.64,339.79,735.75,930.58,456.5,9834.15,9203.99,4019.64,9083.35,10104.64,9994.67,9494.93,4321.13
silverstone,5158.08,4815.75,16947.24,9175.17,4030.59,7043.58,1273.39,1119.23,1194.5,5137.22,1254.64,0.0,1531.29,519.16,379.97,1039.46,10902.52,9507.1,5265.91,7833.25,8850.16,9522.78,8320.08,5561.34
hungaroring,3628.99,3387.79,15546.43,8302.58,2557.38,8573.8,683.89,1012.39,1497.97,6644.71,339.79,1531.29,0.0,1017.59,1176.82,791.59,9497.82,8932.77,3736.23,9326.34,10369.44,10294.52,9665.43,4030.09
spa,4640.39,4307.69,16511.75,8926.2,3545.36,7556.53,803.27,753.28,1026.45,5655.01,735.75,519.16,1017.59,0.0,238.6,589.79,10454.3,9366.3,4748.5,8349.22,9369.31,9728.9,8800.87,5045.72
zandvoort,4805.05,4515.1,16572.56,8867.67,3652.58,7408.92,1038.66,985.59,1215.2,5470.23,930.58,379.97,1176.82,238.6,0.0,828.29,10524.12,9257.66,4911.89,8157.7,9192.92,9807.54,8577.84,5202.61
monza,4242.73,3797.55,16288.08,9058.02,3314.42,7945.2,238.09,255.69,722.01,6134.6,456.5,1039.46,791.59,589.79,828.29,0.0,10260.98,9620.28,4353.36,8837.12,9819.62,9554.71,9359.49,4665.48
marina_bay,6327.19,7353.82,6057.69,3806.81,6946.64,16953.2,10077.87,10425.06,10873.36,14805.77,9834.15,10902.52,9497.82,10454.3,10524.12,10260.98,0.0,5035.99,6219.25,15843.05,16613.29,15982.61,14219.85,5882.34
suzuka,8054.34,9293.32,8129.72,1477.81,7342.55,12224.22,9598.52,9874.96,10323.61,10584.02,9203.99,9507.1,8932.77,9366.3,9257.66,9620.28,5035.99,0.0,8003.99,10829.0,11598.8,18737.43,9185.21,7787.89
losail,112.11,1329.13,12000.56,6741.58,1661.51,12295.53,4129.25,4444.17,4822.99,10362.82,4019.64,5265.91,3736.23,4748.5,4911.89,4353.36,6219.25,8003.99,0.0,13008.46,14094.27,11883.61,13022.63,337.14
americas,12908.78,12632.62,14286.08,12043.14,11489.38,1767.69,9074.91,8824.3,8582.43,2703.19,9083.35,7833.25,9326.34,8349.22,8157.7,8837.12,15843.05,10829.0,13008.46,0.0,1201.87,8085.18,1759.61,13260.64
rodriguez,13990.13,13574.58,13563.81,12920.89,12631.93,2064.12,10054.68,9778.21,9487.42,3731.54,10104.64,8850.16,10369.44,9369.31,9192.92,9819.62,16613.29,11598.8,14094.27,1201.87,0.0,7430.98,2433.22,14366.08
interlagos,11813.59,10555.63,13062.93,18553.96,12217.83,6596.17,9612.48,9306.38,8834.87,8159.68,9994.67,9522.78,10294.52,9728.9,9807.54,9554.71,15982.61,18737.43,11883.61,8085.18,7430.98,0.0,9787.88,12149.09
vegas,12943.28,13047.49,13131.15,10488.07,11373.52,3492.74,9592.05,9413.94,9288.44,3612.76,9494.93,8320.08,9665.43,8800.87,8577.84,9359.49,14219.85,9185.21,13022.63,1759.61,2433.22,9787.88,0.0,13193.63
yas_marina,446.84,1615.85,11674.76,6494.1,1823.13,12600.1,4443.94,4763.03,5148.63,10635.91,4321.13,5561.34,4030.09,5045.72,5202.61,4665.48,5882.34,7787.89,337.14,13260.64,14366.08,12149.09,13193.63,0.0

In [22]:
distances.to_csv("Circuit_Distances.csv")

In [23]:
distances = pd.read_csv("Circuit_Distances.csv", index_col=0)

distances

,bahrain,jeddah,albert_park,shanghai,baku,miami,imola,monaco,catalunya,villeneuve,red_bull_ring,silverstone,hungaroring,spa,zandvoort,monza,marina_bay,suzuka,losail,americas,rodriguez,interlagos,vegas,yas_marina
bahrain,0.00,1258.43,12112.63,6804.82,1595.70,12185.63,4018.27,4332.65,4710.93,10258.97,3910.84,5158.08,3628.99,4640.39,4805.05,4242.73,6327.19,8054.34,112.11,12908.78,13990.13,11813.59,12943.28,446.84
jeddah,1258.43,0.00,12817.12,8062.08,2317.68,11605.63,3559.50,3810.52,4087.37,9929.43,3585.08,4815.75,3387.79,4307.69,4515.10,3797.55,7353.82,9293.32,1329.13,12632.62,13574.58,10555.63,13047.49,1615.85
albert_park,12112.63,12817.12,0.00,8078.46,12989.08,15594.50,16086.36,16422.24,16823.35,16741.10,15878.75,16947.24,15546.43,16511.75,16572.56,16288.08,6057.69,8129.72,12000.56,14286.08,13563.81,13062.93,13131.15,11674.76
shanghai,6804.82,8062.08,8078.46,0.00,6336.88,13248.55,8986.37,9302.00,9779.98,11342.35,8611.28,9175.17,8302.58,8926.20,8867.67,9058.02,3806.81,1477.81,6741.58,12043.14,12920.89,18553.96,10488.07,6494.10
baku,1595.70,2317.68,12989.08,6336.88,0.00,11015.93,3135.79,3484.89,3946.50,8930.53,2890.55,4030.59,2557.38,3545.36,3652.58,3314.42,6946.64,7342.55,1661.51,11489.38,12631.93,12217.83,11373.52,1823.13
miami,12185.63,11605.63,15594.50,13248.55,11015.93,0.00,8172.92,7870.83,7536.29,2253.88,8278.97,7043.58,8573.80,7556.53,7408.92,7945.20,16953.20,12224.22,12295.53,1767.69,2064.12,6596.17,3492.74,12600.10
imola,4018.27,3559.50,16086.36,8986.37,3135.79,8172.92,0.00,349.98,828.38,6372.27,397.58,1273.39,683.89,803.27,1038.66,238.09,10077.87,9598.52,4129.25,9074.91,10054.68,9612.48,9592.05,4443.94
monaco,4332.65,3810.52,16422.24,9302.00,3484.89,7870.83,349.98,0.00,485.64,6121.74,690.95,1119.23,1012.39,753.28,985.59,255.69,10425.06,9874.96,4444.17,8824.30,9778.21,9306.38,9413.94,4763.03
catalunya,4710.93,4087.37,16823.35,9779.98,3946.50,7536.29,828.38,485.64,0.00,5891.51,1173.27,1194.50,1497.97,1026.45,1215.20,722.01,10873.36,10323.61,4822.99,8582.43,9487.42,8834.87,9288.44,5148.63
villeneuve,10258.97,9929.43,16741.10,11342.35,8930.53,2253.88,6372.27,6121.74,5891.51,0.00,6390.49,5137.22,6644.71,5655.01,5470.23,6134.60,14805.77,10584.02,10362.82,2703.19,3731.54,8159.68,3612.76,10635.91
red_bull_ring,3910.84,3585.08,15878.75,8611.28,2890.55,8278.97,397.58,690.95,1173.27,6390.49,0.00,1254.64,339.79,735.75,930.58,456.50,9834.15,9203.99,4019.64,9083.35,10104.64,9994.67,9494.93,4321.13
silverstone,5158.08,4815.75,16947.24,9175.17,4030.59,7043.58,1273.39,1119.23,1194.50,5137.22,1254.64,0.00,1531.29,519.16,379.97,1039.46,10902.52,9507.10,5265.91,7833.25,8850.16,9522.78,8320.08,5561.34
hungaroring,3628.99,3387.79,15546.43,8302.58,2557.38,8573.80,683.89,1012.39,1497.97,6644.71,339.79,1531.29,0.00,1017.59,1176.82,791.59,9497.82,8932.77,3736.23,9326.34,10369.44,10294.52,9665.43,4030.09
spa,4640.39,4307.69,16511.75,8926.20,3545.36,7556.53,803.27,753.28,1026.45,5655.01,735.75,519.16,1017.59,0.00,238.60,589.79,10454.30,9366.30,4748.50,8349.22,9369.31,9728.90,8800.87,5045.72
zandvoort,4805.05,4515.10,16572.56,8867.67,3652.58,7408.92,1038.66,985.59,1215.20,5470.23,930.58,379.97,1176.82,238.60,0.00,828.29,10524.12,9257.66,4911.89,8157.70,9192.92,9807.54,8577.84,5202.61
monza,4242.73,3797.55,16288.08,9058.02,3314.42,7945.20,238.09,255.69,722.01,6134.60,456.50,1039.46,791.59,589.79,828.29,0.00,10260.98,9620.28,4353.36,8837.12,9819.62,9554.71,9359.49,4665.48
marina_bay,6327.19,7353.82,6057.69,3806.81,6946.64,16953.20,10077.87,10425.06,10873.36,14805.77,9834.15,10902.52,9497.82,10454.30,10524.12,10260.98,0.00,5035.99,6219.25,15843.05,16613.29,15982.61,14219.85,5882.34
suzuka,8054.34,9293.32,8129.72,1477.81,7342.55,12224.22,9598.52,9874.96,10323.61,10584.02,9203.99,9507.10,8932.77,9366.30,9257.66,9620.28,5035.99,0.00,8003.99,10829.00,11598.80,18737.43,9185.21,7787.89
losail,112.11,1329.13,12000.56,6741.58,1661.51,12295.53,4129.25,4444.17,4822.99,10362.82,4019.64,5265.91,3736.23,4748.50,4911.89,4353.36,6219.25,8003.99,0.00,13008.46,14094.27,11883.61,13022.63,337.14
americas,12908.78,12632.62,14286.08,12043.14,11489.38,1767.69,9074.91,8824.30,8582.43,2703.19,9083.35,7833.25,9326.34,8349.22,8157.70,8837.12,15843.05,10829.00,13008.46,0.00,1201.87,8085.18,1759.61,13260.64
rodriguez,13990.13,13574.58,13563.81,12920.89,12631.93,2064.12,10054.68,9778.21,9487.42,3731.54,10104.64,8850.16,10369.44,9369.31,9192.92,9819.62,16613.29,11598.80,14094.27,1201.87,0.00,7430.98,2433.22,14366.08
interlagos,11813.59,10555.63,13062.93,18553.96,12217.83,6596.17,9612.48,9306.38,8834.87,8159.68,9994.67,9522.78,10294.52,9728.90,9807.54,9554.71,15982.61,18737.43,11883.61,8085.18,7430.98,0.00,9787.88,12149.09
vegas,12943.28,13047.49,13131.15,10488.07,11373.52,3492.74,9592.05,9413.94,9288.44,3612.76,9494.93,8320.08,9665.43,8800.87,8577.84,9359.49,14219.85,9185.21,13022.63,1759.61,2433.22,9787.88,0.00,13193.63
yas_marina,446.84,1615.85,11674.76,6494.10,1823.13,12600.10,4443.94,4763.03,5148.63,10635.91,4321.13,5561.34,4030.09,5045.72,5202.61,4665.48,5882.34,7787.89,337.14,13260.64,14366.08,12149.09,13193.63,0.00

In [ ]:
bah = distances.loc['bahrain']

bah = bah.sort_values()

bah[1:4].keys().tolist()

In [24]:
for cir in circuits:
    print(cir, '-', distances.loc[cir].sort_values().keys().tolist()[1])
    print()

bahrain - losail

jeddah - bahrain

albert_park - marina_bay

shanghai - suzuka

baku - bahrain

miami - americas

imola - monza

monaco - monza

catalunya - monaco

villeneuve - miami

red_bull_ring - hungaroring

silverstone - zandvoort

hungaroring - red_bull_ring

spa - zandvoort

zandvoort - spa

monza - imola

marina_bay - shanghai

suzuka - shanghai

losail - bahrain

americas - rodriguez

rodriguez - americas

interlagos - miami

vegas - americas

yas_marina - losail

In [ ]:
for circuit in circuits:
    nearest_calendar(circuit, display=True)
    print()

In [25]:
min_tot = float("inf")

for circuit in circuits:
    parsed, total = nearest_calendar(circuit, circuits)
    
    #total = total + 2*(distances.loc['silverstone', circuit])
    
    print(circuit, round(total, 2), "kms")
    
    if total < min_tot:
        min_tot = total
        best_start = circuit

print("\nBest start :", best_start)
print("Total distance :", round(min_tot, 2), "kms")

bahrain 56686.3 kms
jeddah 55834.33 kms
albert_park 51677.02 kms
shanghai 57985.38 kms
baku 56794.73 kms
miami 57997.16 kms
imola 59879.85 kms
monaco 61111.91 kms
catalunya 60487.14 kms
villeneuve 59821.14 kms
red_bull_ring 60782.31 kms
silverstone 59456.11 kms
hungaroring 60496.0 kms
spa 59905.78 kms
zandvoort 60044.97 kms
monza 59974.14 kms
marina_bay 58682.26 kms
suzuka 56756.2 kms
losail 56796.0 kms
americas 61297.11 kms
rodriguez 57689.72 kms
interlagos 51530.4 kms
vegas 56261.1 kms
yas_marina 56328.88 kms

Best start : interlagos
Total distance : 51530.4 kms

In [26]:
nearest_calendar('interlagos', circuits, display=True)

interlagos 0
miami 6596.17 kms
americas 1767.69 kms
rodriguez 1201.87 kms
vegas 2433.22 kms
villeneuve 3612.76 kms
silverstone 5137.22 kms
zandvoort 379.97 kms
spa 238.6 kms
monza 589.79 kms
imola 238.09 kms
monaco 349.98 kms
catalunya 485.64 kms
red_bull_ring 1173.27 kms
hungaroring 339.79 kms
baku 2557.38 kms
bahrain 1595.7 kms
losail 112.11 kms
yas_marina 337.14 kms
jeddah 1615.85 kms
marina_bay 7353.82 kms
shanghai 3806.81 kms
suzuka 1477.81 kms
albert_park 8129.72 kms

Total distance : 51530.4 kms

In [27]:
concorde

['São Paulo',
 'Miami',
 'Mexico City',
 'Austin',
 'Las Vegas',
 'Montreal',
 'Silverstone',
 'Zandvoort',
 'Spa',
 'Montmeló',
 'Monte-Carlo',
 'Monza',
 'Imola',
 'Spielberg',
 'Budapest',
 'Jeddah',
 'Sakhir',
 'Al Daayen',
 'Abu Dhabi',
 'Baku',
 'Suzuka',
 'Shanghai',
 'Marina Bay',
 'Melbourne']

In [29]:
from python_tsp.exact import solve_tsp_dynamic_programming

In [34]:
from python_tsp.distances import great_circle_distance_matrix
from python_tsp.exact import solve_tsp_dynamic_programming
from python_tsp.heuristics import solve_tsp_simulated_annealing
from python_tsp.heuristics import solve_tsp_local_search

In [31]:
coords = list()
locs = dict.fromkeys(circuits, 0)

for index, row in f1_23.iterrows():
    lat = row['lat']
    lng = row['lng']
    
    #coords.append([lat, lng])

    locs[row['circuitRef']] = [lat, lng]
    
print(len(locs))
print(list(locs.values()))

sources = np.array(list(locs.values()))

24
[[26.0325, 50.5106], [21.6319, 39.1044], [-37.8497, 144.968], [31.3389, 121.22], [40.3725, 49.8533], [25.9581, -80.2389], [44.3439, 11.7167], [43.7347, 7.42056], [41.57, 2.26111], [45.5, -73.5228], [47.2197, 14.7647], [52.0786, -1.01694], [47.5789, 19.2486], [50.4372, 5.97139], [52.3888, 4.54092], [45.6156, 9.28111], [1.2914, 103.864], [34.8431, 136.541], [25.49, 51.4542], [30.1328, -97.6411], [19.4042, -99.0907], [-23.7036, -46.6997], [36.1147, -115.173], [24.4672, 54.6031]]

In [33]:
locs

{'bahrain': [26.0325, 50.5106],
 'jeddah': [21.6319, 39.1044],
 'albert_park': [-37.8497, 144.968],
 'shanghai': [31.3389, 121.22],
 'baku': [40.3725, 49.8533],
 'miami': [25.9581, -80.2389],
 'imola': [44.3439, 11.7167],
 'monaco': [43.7347, 7.42056],
 'catalunya': [41.57, 2.26111],
 'villeneuve': [45.5, -73.5228],
 'red_bull_ring': [47.2197, 14.7647],
 'silverstone': [52.0786, -1.01694],
 'hungaroring': [47.5789, 19.2486],
 'spa': [50.4372, 5.97139],
 'zandvoort': [52.3888, 4.54092],
 'monza': [45.6156, 9.28111],
 'marina_bay': [1.2914, 103.864],
 'suzuka': [34.8431, 136.541],
 'losail': [25.49, 51.4542],
 'americas': [30.1328, -97.6411],
 'rodriguez': [19.4042, -99.0907],
 'interlagos': [-23.7036, -46.6997],
 'vegas': [36.1147, -115.173],
 'yas_marina': [24.4672, 54.6031]}

In [32]:
sources

array([[  26.0325 ,   50.5106 ],
       [  21.6319 ,   39.1044 ],
       [ -37.8497 ,  144.968  ],
       [  31.3389 ,  121.22   ],
       [  40.3725 ,   49.8533 ],
       [  25.9581 ,  -80.2389 ],
       [  44.3439 ,   11.7167 ],
       [  43.7347 ,    7.42056],
       [  41.57   ,    2.26111],
       [  45.5    ,  -73.5228 ],
       [  47.2197 ,   14.7647 ],
       [  52.0786 ,   -1.01694],
       [  47.5789 ,   19.2486 ],
       [  50.4372 ,    5.97139],
       [  52.3888 ,    4.54092],
       [  45.6156 ,    9.28111],
       [   1.2914 ,  103.864  ],
       [  34.8431 ,  136.541  ],
       [  25.49   ,   51.4542 ],
       [  30.1328 ,  -97.6411 ],
       [  19.4042 ,  -99.0907 ],
       [ -23.7036 ,  -46.6997 ],
       [  36.1147 , -115.173  ],
       [  24.4672 ,   54.6031 ]])

In [35]:
distance_matrix = great_circle_distance_matrix(sources)

In [64]:
print(distance_matrix)

[[       0.          1258429.83843825 12112617.73966088  6804815.03061091
   1595693.56258888 12185612.75618915  4018262.77893379  4332644.24048384
   4710923.52165113 10258952.64898581  3910831.08547854  5158073.7384032
   3628983.50129379  4640381.6465967   4805046.61876813  4242719.14190751
   6327184.89354457  8054333.75877771   112107.71709305 12908757.91325511
  13990115.65079406 11813578.60456993 12943261.85682142   446841.63279017]
 [ 1258429.83843825        0.         12817101.72056811  8062066.6136193
   2317672.21980928 11605609.91553419  3559492.38605212  3810511.66314386
   4087366.14049021  9929414.59430671  3585074.25724148  4815746.74975249
   3387787.3402735   4307683.17367224  4515092.16673147  3797542.25245785
   7353808.88214332  9293305.03104639  1329128.75443798 12632600.06517958
  13574557.82454665 10555616.34444338 13047474.92639043  1615852.75453504]
 [12112617.73966088 12817101.72056811        0.          8078453.51737378
  12989064.13406629 15594474.5214946  16086339.3596154  16422212.79689612
  16823326.93142675 16741081.3673824  15878730.474119   16947218.44112767
  15546405.1000299  16511725.33093711 16572538.51319322 16288056.76753515
   6057681.4413666   8129708.70299669 12000539.67974279 14286058.34570664
  13563789.31015689 13062910.86871624 13131134.56681503 11674748.86231754]
 [ 6804815.03061091  8062066.6136193   8078453.51737378        0.
   6336875.36702851 13248535.04519329  8986357.44019321  9301983.10065425
   9779963.60531388 11342333.94235338  8611269.74176559  9175158.24774564
   8302567.77555925  8926189.46627237  8867658.19359531  9058008.80229346
   3806806.99253141  1477811.71897181  6741568.95270936 12043125.39492099
  12920872.45533675 18553930.62178503 10488059.38134675  6494087.5163902 ]
 [ 1595693.56258888  2317672.21980928 12989064.13406629  6336875.36702851
         0.         11015918.06550786  3135782.26643821  3484881.71449936
   3946495.94785897  8930516.88827254  2890541.53124959  4030586.09718196
   2557379.39018248  3545359.42382656  3652579.06977881  3314417.66886277
   6946630.23390323  7342544.79557517  1661503.81668183 11489359.4175804
  12631912.75454032 12217817.3469142  11373508.24632073  1823132.08923551]
 [12185612.75618915 11605609.91553419 15594474.5214946  13248535.04519329
  11015918.06550786        0.          8172907.60872093  7870814.69598995
   7536276.01816903  2253881.77597536  8278957.02453237  7043571.57712455
   8573787.98601493  7556520.01878188  7408905.48897448  7945184.67083086
  16953180.65509776 12224201.0908952  12295513.55555032  1767691.89261811
   2064119.51674087  6596156.67399851  3492737.78755387 12600080.91107758]
 [ 4018262.77893379  3559492.38605212 16086339.3596154   8986357.44019321
   3135782.26643821  8172907.60872093        0.           349980.56490353
    828382.15646637  6372258.96117556   397576.29622067  1273385.28665963
    683891.3286936    803265.07121062  1038658.38241003   238088.47684759
  10077858.16915536  9598509.15371727  4129249.05836604  9074895.8221087
  10054668.75274552  9612464.69096509  9592033.05820279  4443930.70711016]
 [ 4332644.24048384  3810511.66314386 16422212.79689612  9301983.10065425
   3484881.71449936  7870814.69598995   349980.56490353        0.
    485641.29395136  6121729.24742564   690951.1467292   1119233.40993985
   1012393.3927011    753276.21376715   985588.80501908   255688.85291356
  10425047.29567118  9874943.21907933  4444163.43689058  8824286.07296678
   9778196.93557005  9306365.83174289  9413927.6013427   4763023.9975384 ]
 [ 4710923.52165114  4087366.14049021 16823326.93142675  9779963.60531388
   3946495.94785897  7536276.01816903   828382.15646637   485641.29395136
         0.          5891504.9721924   1173272.7537019   1194497.1701065
   1497967.24328552  1026444.45320572  1215201.24112143   722010.4664335
  10873349.3339848  10323593.21252466  4822981.11301787  8582422.50900945
   9487402.57517081  8834853.31596768  9288424.22819896  5148621.97514899]
 [10258952.64898581  9929414.59430671 16741081.3673824  11342333.94235338
   8930516.88827254  2253881.77597536  6372258.96117556  6121729.24742564
   5891504.9721924         0.          6390485.49373741  5137213.07762582
   6644698.62419567  5654998.81925307  5470224.75086736  6134596.39590339
  14805753.97955448 10584002.86236485 10362809.70654296  2703186.1663279
   3731537.84769971  8159666.45974123  3612757.39955104 10635892.42363877]
 [ 3910831.08547854  3585074.25724148 15878730.474119    8611269.74176559
   2890541.53124959  8278957.02453237   397576.29622067   690951.1467292
   1173272.7537019   6390485.49373741        0.          1254640.11647602
    339792.4380077    735750.78485093   930575.37605571   456503.09435966
   9834132.94927515  9203978.08311297  4019634.82500049  9083339.69189413
  10104621.17940418  9994655.08077103  9494912.6096466   4321125.8870022 ]
 [ 5158073.7384032   4815746.74975249 16947218.44112767  9175158.24774564
   4030586.09718196  7043571.57712455  1273385.28665963  1119233.40993985
   1194497.1701065   5137213.07762582  1254640.11647602        0.
   1531284.0545293    519163.18246218   379966.15027535  1039454.42791295
  10902502.47412573  9507085.69535926  5265906.35282687  7833240.6131615
   8850152.63186852  9522763.38860154  8320068.84181537  5561331.85303323]
 [ 3628983.50129379  3387787.3402735  15546405.1000299   8302567.77555925
   2557379.39018248  8573787.98601493   683891.3286936   1012393.3927011
   1497967.24328552  6644698.62419567   339792.4380077   1531284.0545293
         0.          1017592.77300497  1176815.23928445   791589.94817286
   9497806.26995966  8932756.76012114  3736220.99645371  9326329.48505255
  10369429.70047874 10294506.8814053   9665412.15607668  4030081.63919977]
 [ 4640381.6465967   4307683.17367224 16511725.33093711  8926189.46627237
   3545359.42382656  7556520.01878188   803265.07121062   753276.21376715
   1026444.45320572  5654998.81925307   735750.78485093   519163.18246218
   1017592.77300497        0.           238597.36660419   589784.48640093
  10454283.94351049  9366289.25812641  4748490.05419257  8349210.83125991
   9369298.54143823  9728887.00674148  8800852.99122676  5045716.55983998]
 [ 4805046.61876813  4515092.16673147 16572538.51319322  8867658.19359531
   3652579.06977881  7408905.48897448  1038658.38241003   985588.80501908
   1215201.24112143  5470224.75086736   930575.37605571   379966.15027535
   1176815.23928445   238597.36660419        0.           828289.12266049
  10524102.50246608  9257644.78789241  4911884.52946709  8157685.85606449
   9192905.34906232  9807530.3755176   8577828.21846451  5202605.94142529]
 [ 4242719.14190751  3797542.25245785 16288056.76753515  9058008.80229346
   3314417.66886277  7945184.67083086   238088.47684759   255688.85291356
    722010.4664335   6134596.39590339   456503.09435966  1039454.42791295
    791589.94817286   589784.48640093   828289.12266049        0.
  10260970.11810962  9620262.62572159  4353357.13099079  8837104.94066903
   9819602.42464085  9554693.92115262  9359478.10034381  4665470.22986748]
 [ 6327184.89354457  7353808.88214332  6057681.4413666   3806806.99253141
   6946630.23390323 16953180.65509776 10077858.16915536 10425047.29567118
  10873349.3339848  14805753.97955448  9834132.94927515 10902502.47412573
   9497806.26995966 10454283.94351049 10524102.50246608 10260970.11810962
         0.          5035978.72180777  6219244.98274187 15843027.94067096
  16613267.24188256 15982589.25171122 14219829.13496409  5882329.66686467]
 [ 8054333.75877771  9293305.03104639  8129708.70299669  1477811.71897181
   7342544.79557517 12224201.0908952   9598509.15371727  9874943.21907933
  10323593.21252466 10584002.86236485  9203978.08311297  9507085.69535926
   8932756.76012114  9366289.25812641  9257644.78789241  9620262.62572159
   5035978.72180777        0.          8003978.41191594 10828985.68925883
  11598786.6697199  18737408.94319064  9185195.64797264  7787876.02922119]
 [  112107.71709304  1329128.75443798 12000539.67974279  6741568.95270936
   1661503.81668183 12295513.55555032  4129249.05836604  4444163.43689058
   4822981.11301787 10362809.70654296  4019634.82500049  5265906.35282687
   3736220.99645371  4748490.05419257  4911884.52946709  4353357.13099079
   6219244.98274187  8003978.41191594        0.         13008444.56482816
  14094254.55138126 11883596.083915   13022610.34976182   337139.30829247]
 [12908757.9132551  12632600.06517958 14286058.34570664 12043125.39492099
  11489359.4175804   1767691.89261811  9074895.8221087   8824286.07296678
   8582422.50900945  2703186.1663279   9083339.69189413  7833240.6131615
   9326329.48505255  8349210.83125991  8157685.85606449  8837104.94066903
  15843027.94067096 10828985.68925883 13008444.56482816        0.
   1201867.7065993   8085170.43584366  1759611.0842387  13260617.96204219]
 [13990115.65079406 13574557.82454665 13563789.31015689 12920872.45533675
  12631912.75454032  2064119.51674087 10054668.75274552  9778196.93557005
   9487402.57517081  3731537.84769971 10104621.17940418  8850152.63186852
  10369429.70047874  9369298.54143823  9192905.34906232  9819602.42464085
  16613267.24188256 11598786.6697199  14094254.55138126  1201867.7065993
         0.          7430971.65392761  2433214.10437167 14366059.90315686]
 [11813578.60456993 10555616.34444338 13062910.86871624 18553930.62178503
  12217817.3469142   6596156.67399851  9612464.69096509  9306365.83174289
   8834853.31596768  8159666.45974123  9994655.08077103  9522763.38860154
  10294506.8814053   9728887.00674148  9807530.3755176   9554693.92115262
  15982589.25171122 18737408.94319064 11883596.083915    8085170.43584366
   7430971.65392761        0.          9787868.68506302 12149075.25618526]
 [12943261.85682141 13047474.92639043 13131134.56681503 10488059.38134675
  11373508.24632073  3492737.78755387  9592033.05820279  9413927.6013427
   9288424.22819896  3612757.39955105  9494912.6096466   8320068.84181537
   9665412.15607668  8800852.99122676  8577828.21846451  9359478.10034381
  14219829.13496409  9185195.64797264 13022610.34976182  1759611.0842387
   2433214.10437167  9787868.68506302        0.         13193610.86973597]
 [  446841.63279017  1615852.75453504 11674748.86231754  6494087.5163902
   1823132.08923551 12600080.91107758  4443930.70711016  4763023.9975384
   5148621.97514899 10635892.42363877  4321125.8870022   5561331.85303323
   4030081.63919977  5045716.55983998  5202605.94142529  4665470.22986748
   5882329.66686467  7787876.02922119   337139.30829247 13260617.96204219
  14366059.90315686 12149075.25618526 13193610.86973597        0.        ]]

In [66]:
np.savetxt("Distance_Matrix.csv", distance_matrix, delimiter=',')

In [105]:
permutation, distance = solve_tsp_simulated_annealing(distance_matrix)

print(permutation)
print()
print(distance)

[0, 1, 4, 12, 10, 6, 15, 7, 8, 13, 14, 11, 9, 22, 19, 20, 5, 21, 2, 16, 17, 3, 23, 18]

62444719.52784853

In [127]:
min_tot = float("inf")

for i in range(0, 30):
    if min_tot == t:
        print(i, min_tot)
        break
    permutation, distance = solve_tsp_simulated_annealing(distance_matrix)
    if distance < min_tot:
        min_perm = permutation
        min_tot = distance

3 62399872.89727439

In [138]:
permutation, distance = solve_tsp_local_search(distance_matrix)

print(permutation)
print(distance)

[0, 1, 12, 10, 6, 15, 7, 8, 13, 14, 11, 9, 22, 19, 20, 5, 21, 2, 16, 3, 17, 4, 23, 18]
62399872.89727439

In [110]:
print(min_perm)
print()
print(min_tot)

[0, 1, 12, 10, 6, 15, 7, 8, 13, 14, 11, 9, 22, 19, 20, 5, 21, 2, 16, 3, 17, 4, 23, 18]

62399872.89727439

In [111]:
t = min_tot

In [40]:
for i in range(0, len(circuits)):
    print(i, circuits[i])

0 bahrain
1 jeddah
2 albert_park
3 shanghai
4 baku
5 miami
6 imola
7 monaco
8 catalunya
9 villeneuve
10 red_bull_ring
11 silverstone
12 hungaroring
13 spa
14 zandvoort
15 monza
16 marina_bay
17 suzuka
18 losail
19 americas
20 rodriguez
21 interlagos
22 vegas
23 yas_marina

In [63]:
for i in min_perm:
    print(i, circuits[i])

0 bahrain
1 jeddah
12 hungaroring
10 red_bull_ring
6 imola
15 monza
7 monaco
8 catalunya
13 spa
14 zandvoort
11 silverstone
9 villeneuve
22 vegas
19 americas
20 rodriguez
5 miami
21 interlagos
2 albert_park
16 marina_bay
3 shanghai
17 suzuka
4 baku
23 yas_marina
18 losail

In [85]:
optimal_perm = min_perm + [min_perm[0]]

In [78]:
high = 0

for i in range(0, len(min_perm)-1):
    loc1 = circuits[min_perm[i]]
    loc2 = circuits[min_perm[i+1]]
    dist = distances.loc[loc1, loc2]
    print(loc1, loc2, dist)
    
    if dist > high:
        max1 = i
        max2 = i+1
        high = dist
        
print()
print(max1, max2, high)
print(min_perm[max1], min_perm[max2])

bahrain jeddah 1258.43
jeddah hungaroring 3387.79
hungaroring red_bull_ring 339.79
red_bull_ring imola 397.58
imola monza 238.09
monza monaco 255.69
monaco catalunya 485.64
catalunya spa 1026.45
spa zandvoort 238.6
zandvoort silverstone 379.97
silverstone villeneuve 5137.22
villeneuve vegas 3612.76
vegas americas 1759.61
americas rodriguez 1201.87
rodriguez miami 2064.12
miami interlagos 6596.17
interlagos albert_park 13062.93
albert_park marina_bay 6057.69
marina_bay shanghai 3806.81
shanghai suzuka 1477.81
suzuka baku 7342.55
baku yas_marina 1823.13
yas_marina losail 337.14

16 17 13062.93
21 2

In [81]:
least = min_perm[max2:] + min_perm[:max1+1]

print(least, len(least))

[2, 16, 3, 17, 4, 23, 18, 0, 1, 12, 10, 6, 15, 7, 8, 13, 14, 11, 9, 22, 19, 20, 5, 21] 24

In [86]:
for i in least:
    print(i, circuits[i])

2 albert_park
16 marina_bay
3 shanghai
17 suzuka
4 baku
23 yas_marina
18 losail
0 bahrain
1 jeddah
12 hungaroring
10 red_bull_ring
6 imola
15 monza
7 monaco
8 catalunya
13 spa
14 zandvoort
11 silverstone
9 villeneuve
22 vegas
19 americas
20 rodriguez
5 miami
21 interlagos

In [142]:
tot = 0

for i in range(0, len(least)-1):
    loc1 = circuits[least[i]]
    loc2 = circuits[least[i+1]]
    
    tot = tot + distances.loc[loc1, loc2]
    
print(round(tot, 2))

49337.02

In [87]:
concorde[::-1]

['Melbourne',
 'Marina Bay',
 'Shanghai',
 'Suzuka',
 'Baku',
 'Abu Dhabi',
 'Al Daayen',
 'Sakhir',
 'Jeddah',
 'Budapest',
 'Spielberg',
 'Imola',
 'Monza',
 'Monte-Carlo',
 'Montmeló',
 'Spa',
 'Zandvoort',
 'Silverstone',
 'Montreal',
 'Las Vegas',
 'Austin',
 'Mexico City',
 'Miami',
 'São Paulo']

In [ ]:
nearest_calendar('Melbourne', display=True)

In [ ]:
nearest_calendar('Silverstone', display=True)

In [ ]:
nearest_calendar('Monte-Carlo', display=True)

In [ ]:
def loc_rank(start, locations):
    
    lat1 = f1_23.loc[f1_23['location'] == start, 'lat'].values[0]
    lng1 = f1_23.loc[f1_23['location'] == start, 'lng'].values[0]
    
    rank = {}
    
    
    for location in locations:
        lat2 = f1_23.loc[f1_23['location'] == location, 'lat'].values[0]
        lng2 = f1_23.loc[f1_23['location'] == location, 'lng'].values[0]
        
        distance = dist(lat1, lng1, lat2, lng2)
        
        rank[location] = distance
    
    ranked = dict(sorted(rank.items(), key=lambda item: item[1]))
    #s = ranked.pop(start)
    
    #print(ranked)
    return ranked

In [ ]:
for location in locations:
    rank = loc_rank(location, locations)
    print("\n", location, "\n", rank, "\n")

In [ ]:
loc = 'Sakhir'

rank = loc_rank(loc, locations)

rank

In [ ]:
ranks = list(rank.keys())

ranks[5]

In [ ]:
def dist_rank(start, loc, parsed, display=False):
    loc_list = list(set(locations) - set(parsed))
    
    rank = loc_rank(start, loc_list)
    
    if display == True:
        print("\n", rank, "\n")
    rank_list = list(rank.keys())
    
    for i in range(0, len(rank_list)):
        if rank_list[i] == loc:
            return i+1, len(rank_list)

In [ ]:
dist_rank('Sakhir', 'Jeddah', ['Sakhir'])

In [ ]:
i = 1
start = locations[0]

print(f"{i:<2} {start :<20}\n")

for location in locations[1:]:
    i = i + 1
    
    perf, left = dist_rank(start, location, [start], display=True)
    start = location
    
    #print(i, location, " | Rank :", perf)
    print(f"{i:<2} {location :<20} {perf:>5}/{left:>2}\n")

In [ ]:
parsed = list()

i = 1
start = locations[0]

print(f"{i:<2} {start :<20}")

for location in locations[1:]:
    i = i + 1
    
    parsed.append(start)
    
    perf, left = dist_rank(start, location, parsed, display=True)
    start = location
    
    #print(i, location, " | Rank :", perf)
    print(f"{i:<2} {location :<20} {perf:>5}/{left:<2}")

In [ ]:
i = 1
start = locations[0]

print(f"{start :^29}\n")

for location in locations[1:]:
    i = i + 1
    
    from_perf, from_left = dist_rank(start, location, [start])
    to_perf, to_left = dist_rank(location, start, [location])
    start = location
    
    #print(i, location, " | Rank :", perf)
    #print(f"{i:<2} {location :<20} {to_perf:>5}/{to_left:>2} {from_perf:>5}/{from_left:>2}\n")
    print(f"{from_perf:>2} {to_perf:>25}\n")
    print(f"{location :^29}\n")

In [ ]:
parsed = list()

i = 1
start = locations[0]

print(f"{i:<2} {start :<20}\n")

for location in locations[1:]:
    i = i + 1
    
    parsed.append(start)
    
    perf, left = dist_rank(start, location, parsed)
    start = location
    
    #print(i, location, " | Rank :", perf)
    print(f"{i:<2} {location :<20} {perf:>5}/{left:<2}\n")

In [ ]:
race_info = pd.read_csv("Race_Info.csv")

In [ ]:
race_info.shape

In [ ]:
race_info['gap'].value_counts()

In [ ]:
race_info = race_info.loc[race_info['year'] > 1992]

race_info.shape

In [ ]:
race_info['gap'].value_counts()

In [ ]:
race_info.loc[race_info['gap'] == 5]

In [ ]:
race_info.loc[race_info['gap'] == 4]

In [ ]:
for i in range(1993, 2024):
    print(i, race_info.loc[race_info['year'] == i, 'gap'].values)

In [ ]:
f = '%Y-%m-%d'
race_info['date'] = pd.to_datetime(race_info['date'], format=f).dt.date

for index, row in race_info.iterrows():
    race_info.loc[index, 'month'] = race_info.loc[index, 'date'].month

In [ ]:
for i in range(1993, 2024):
    print(i, race_info.loc[(race_info['year'] == i) & (race_info['month'] == 8)].shape[0])

In [ ]:
season_info = pd.read_csv("Season_Info.csv")

season_info.shape

In [ ]:
for i in range(1993, 2024):
    rounds = season_info.loc[season_info['year'] == i, 'rounds'].values[0]
    single = season_info.loc[season_info['year'] == i, 'single'].values[0]
    double = season_info.loc[season_info['year'] == i, 'double'].values[0]
    triple = season_info.loc[season_info['year'] == i, 'triple'].values[0]
    
    single = round((single/rounds)*100, 2)
    double = round((double*2/rounds)*100, 2)
    triple = round((triple*3/rounds)*100, 2)
    
    print(i, single, double, triple)

In [ ]:
for index, row in season_info.iterrows():
    
    rounds = row['rounds']
    single = row['single']
    double = row['double']
    triple = row['triple']
    
    season_info.loc[index, 'single %'] = round((single/rounds)*100, 2)
    season_info.loc[index, 'double %'] = round((double*2/rounds)*100, 2)
    season_info.loc[index, 'triple %'] = round((triple*3/rounds)*100, 2)

season_info

In [ ]:
season_info.describe()